# Blinkit Pune Area - NumPy 
# Language: Python
# IDE: Jupyter Notebook


TOPICS WE ARE GOING TO COVER TODAY:
1. Different Ways to Create Arrays
   - Using np.array() with Python lists or tuples
   - Using np.zeros() and np.ones()
   - Using np.arange() for evenly spaced values
   - Using np.random module for random arrays (randint)

2. Slicing in Arrays
   - Basic slicing with : operator
   - Slicing in 1D arrays
   - Slicing in 2D arrays (row and column slicing)
   - Negative indexing in slicing

3. Speed and Performance (Quick Demo)
   - NumPy array operations vs Python lists (speed comparison)


In [ ]:
# STEP 0: IMPORTING REQUIRED LIBRARIES

In [1]:
import numpy as np
import time 

# ============================================================================
# BLINKIT PUNE AREA DATASET DESCRIPTION
# ============================================================================


Our dataset represents Blinkit delivery operations in Pune area.

Dataset columns:
1. Order Value: Total value of the order (in rupees)
2. Customer Ratings: Rating given by customer (out of 5)
3. Number of Items: Total items in the order
4. Distance: Distance from warehouse to customer (in km)
5. Area Code: Different areas in Pune (1, 2, or 3)


## SECTION 1: DIFFERENT WAYS TO CREATE ARRAYS

In [ ]:
print("\n1.1 Creating Arrays using np.arrays")


1.1 Creating Arrays using np.arrays


###  1.1 Using np.array() with Python lists

In [8]:
# Creating 1D Array
order_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108])

In [9]:
order_ids

array([101, 102, 103, 104, 105, 106, 107, 108])

In [10]:
# Check shape of array
print(f"Shape: {order_ids.shape}")


Shape: (8,)


In [11]:
# Creating a 2D array from nested lists
# Each inner list becomes a row

In [14]:
blinkit_data = np.array([
    [450, 4.5, 8, 3.2, 1],    # Order 1
    [320, 4.0, 5, 2.5, 2],    # Order 2
    [680, 5.0, 12, 4.1, 1],   # Order 3
    [210, 3.5, 3, 1.8, 3],    # Order 4
    [550, 4.8, 9, 3.7, 2],    # Order 5
    [890, 4.2, 15, 5.2, 1],   # Order 6
    [340, 3.8, 6, 2.9, 3],    # Order 7
    [720, 4.9, 11, 4.5, 2]    # Order 8
])

In [15]:
blinkit_data

array([[450. ,   4.5,   8. ,   3.2,   1. ],
       [320. ,   4. ,   5. ,   2.5,   2. ],
       [680. ,   5. ,  12. ,   4.1,   1. ],
       [210. ,   3.5,   3. ,   1.8,   3. ],
       [550. ,   4.8,   9. ,   3.7,   2. ],
       [890. ,   4.2,  15. ,   5.2,   1. ],
       [340. ,   3.8,   6. ,   2.9,   3. ],
       [720. ,   4.9,  11. ,   4.5,   2. ]])

In [17]:
blinkit_data.shape

(8, 5)

In [19]:
print("Blinkit Orders Data (2D Array):")
print(blinkit_data)
print(f"Shape: {blinkit_data.shape}")  # (8, 5) means 8 rows, 5 columns
print("Columns: Order Value | Rating | Items | Distance | Area Code")
print()

Blinkit Orders Data (2D Array):
[[450.    4.5   8.    3.2   1. ]
 [320.    4.    5.    2.5   2. ]
 [680.    5.   12.    4.1   1. ]
 [210.    3.5   3.    1.8   3. ]
 [550.    4.8   9.    3.7   2. ]
 [890.    4.2  15.    5.2   1. ]
 [340.    3.8   6.    2.9   3. ]
 [720.    4.9  11.    4.5   2. ]]
Shape: (8, 5)
Columns: Order Value | Rating | Items | Distance | Area Code



### 1.2 Using np.zeros() and np.ones()

- What is np.zeros()?
    - Creates an array filled with zeros.
    - Syntax: np.zeros(shape)

- Why use it?
    - Useful for initializing arrays before filling with actual values.

- Creating a 1D array of zeros

In [21]:
# Creating a 1D array of zeros
pending_orders = np.zeros(8)
print("Pending orders initialized:")
print(pending_orders)
print()

Pending orders initialized:
[0. 0. 0. 0. 0. 0. 0. 0.]



In [24]:
# Creating a 2D array of zeros
delivery_matrix = np.zeros((4, 3), dtype=int)
print("Delivery tracking matrix (4 warehouses, 3 areas):")
print(delivery_matrix)
print()

Delivery tracking matrix (4 warehouses, 3 areas):
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



### What is np.ones()?
    - Creates an array filled with ones.
    - Syntax: np.ones(shape)


In [27]:
active_riders = np.ones(6)
print("Active riders array:")
print(active_riders)
print()

Active riders array:
[1. 1. 1. 1. 1. 1.]



In [29]:
# Practical tip: Create array with any value
base_fee = np.ones(8) * 20  # Rs.20 base fee
print("Base delivery fees (Rs.20 each):")
print(base_fee)
print()

Base delivery fees (Rs.20 each):
[20. 20. 20. 20. 20. 20. 20. 20.]



### 1.3 Using np.arange() for evenly spaced values

**What is np.arange()?**
    
    - Creates an array with evenly spaced values within a range.
    - Syntax: np.arange(start, stop, step)

**Why use it?**
    
    - Quickly create sequences of numbers.

In [33]:
# Creating array from 0 to 9 (stop value NOT included)
order_sequence = np.arange(10)
print("Order sequence (0 to 9):")
print(order_sequence)
print()

Order sequence (0 to 9):
[0 1 2 3 4 5 6 7 8 9]



In [34]:
# Creating array from 100 to 109
order_ids_new = np.arange(100, 110)
print("Order IDs (100 to 109):")
print(order_ids_new)
print()

Order IDs (100 to 109):
[100 101 102 103 104 105 106 107 108 109]



In [35]:
# Creating array with step size
time_slots = np.arange(9, 22, 3)  # 9 AM to 9 PM, 3-hour intervals
print("Delivery time slots (3-hour intervals):")
print(time_slots)
print()

Delivery time slots (3-hour intervals):
[ 9 12 15 18 21]



- Important: The stop value is NEVER included
- arange(1, 10) gives [1, 2, 3, 4, 5, 6, 7, 8, 9], NOT 10

###  1.4 Using np.random for random arrays

 **What is np.random.randint()?**
 
    - Generates random integers from low (inclusive) to high (exclusive).
    - Syntax: np.random.randint(low, high, size)

 **Why use it?**

    - Generate test data and simulate real scenarios.

In [37]:
# Setting random seed for reproducibility
np.random.seed(42)
print("Setting random seed to 42 for consistent results")
print()

Setting random seed to 42 for consistent results



In [38]:
# Generating random order quantities (1 to 20 items)
order_quantities = np.random.randint(1, 21, size=10)
print("Random order quantities (1 to 20 items):")
print(order_quantities)
print()

Random order quantities (1 to 20 items):
[ 7 20 15 11  8  7 19 11 11  4]



In [41]:
# Generating random order quantities (1 to 20 items)
order_quantities = np.random.randint(1, 21, size=10)
print("Random order quantities (1 to 20 items):")
print(order_quantities)
print()

Random order quantities (1 to 20 items):
[12 20  3  5 19  7  9  7 18  4]



In [42]:
# Generating random area codes (1, 2, or 3)
area_codes = np.random.randint(1, 4, size=12)
print("Random area codes (1=Koregaon Park, 2=Hinjewadi, 3=Kothrud):")
print(area_codes)
print()

Random area codes (1=Koregaon Park, 2=Hinjewadi, 3=Kothrud):
[1 2 2 2 1 2 1 2 3 3 1 3]



In [45]:
# Generating a 2D array of random integers
daily_orders = np.random.randint(20, 100, size=(5, 3))
print("Daily order counts (5 days, 3 time slots):")
print(daily_orders)
print()

Daily order counts (5 days, 3 time slots):
[[82 37 63]
 [53 93 81]
 [33 67 34]
 [91 97 81]
 [59 99 72]]



# SECTION 2: SLICING IN ARRAYS

In [49]:
print("\n" + "=" * 60)
print("SECTION 2: SLICING IN ARRAYS")
print("=" * 60)

print('''
- What is slicing?
- Slicing extracts a portion of an array.
- Syntax: array[start:stop:step]
''')

print("\nSlicing allows us to extract portions of arrays efficiently.")
print()


SECTION 2: SLICING IN ARRAYS

- What is slicing?
- Slicing extracts a portion of an array.
- Syntax: array[start:stop:step]


Slicing allows us to extract portions of arrays efficiently.



### 2.1 Slicing in 1D Arrays

In [50]:
order_values = np.array([450, 320, 680, 210, 550, 890, 340, 720, 180, 610])
print("Original array:")
print(order_values)
print()

Original array:
[450 320 680 210 550 890 340 720 180 610]



-  Basic slicing: array[start:stop]
-  Start: Index to begin (inclusive)
-  Stop: Index to end (exclusive)

In [51]:
# First 5 orders
first_five = order_values[0:5]
print("First 5 orders [0:5]:")
print(first_five)
print()


First 5 orders [0:5]:
[450 320 680 210 550]



In [52]:
# Last 5 orders
last_five = order_values[5:10]
print("Last 5 orders [5:10]:")
print(last_five)
print()

Last 5 orders [5:10]:
[890 340 720 180 610]



In [54]:
# Shorthand slicing
first_three = order_values[:3]  # Same as [0:3]
print("First 3 orders [:3]:")
print(first_three)
print()

First 3 orders [:3]:
[450 320 680]



In [55]:
last_three = order_values[7:]  # From index 7 to end
print("Last 3 orders [7:]:")
print(last_three)
print()

Last 3 orders [7:]:
[720 180 610]



In [56]:
# Using step size
every_second = order_values[::2]  # Every 2nd element
print("Every second order [::2]:")
print(every_second)
print()

Every second order [::2]:
[450 680 550 340 180]



### 2.2 Negative Indexing

-  What is negative indexing?
-  Negative indices count from the end of the array.
-  -1 = last element, -2 = second last, etc.

In [57]:
print("Array:")
print(order_values)
print()

Array:
[450 320 680 210 550 890 340 720 180 610]



In [58]:
# Last element
last_order = order_values[-1]
print("Last order [-1]:", last_order)
print()

Last order [-1]: 610



In [59]:
# Last 4 elements
last_four = order_values[-4:]
print("Last 4 orders [-4:]:")
print(last_four)
print()

Last 4 orders [-4:]:
[340 720 180 610]



In [60]:
# All except last 2
all_except_last = order_values[:-2]
print("All except last 2 [:-2]:")
print(all_except_last)
print()

All except last 2 [:-2]:
[450 320 680 210 550 890 340 720]



In [61]:
# Reversing an array
reversed_orders = order_values[::-1]
print("Reversed array [::-1]:")
print(reversed_orders)
print()

Reversed array [::-1]:
[610 180 720 340 890 550 210 680 320 450]



### 2.3 Slicing in 2D Arrays

In [62]:
# Using our Blinkit data
print("Blinkit Orders (8 orders, 5 features):")
print(blinkit_data)
print()

Blinkit Orders (8 orders, 5 features):
[[450.    4.5   8.    3.2   1. ]
 [320.    4.    5.    2.5   2. ]
 [680.    5.   12.    4.1   1. ]
 [210.    3.5   3.    1.8   3. ]
 [550.    4.8   9.    3.7   2. ]
 [890.    4.2  15.    5.2   1. ]
 [340.    3.8   6.    2.9   3. ]
 [720.    4.9  11.    4.5   2. ]]



In [63]:
blinkit_data

array([[450. ,   4.5,   8. ,   3.2,   1. ],
       [320. ,   4. ,   5. ,   2.5,   2. ],
       [680. ,   5. ,  12. ,   4.1,   1. ],
       [210. ,   3.5,   3. ,   1.8,   3. ],
       [550. ,   4.8,   9. ,   3.7,   2. ],
       [890. ,   4.2,  15. ,   5.2,   1. ],
       [340. ,   3.8,   6. ,   2.9,   3. ],
       [720. ,   4.9,  11. ,   4.5,   2. ]])

In [ ]:
# 2D slicing syntax: array[rows, columns]

# Extracting first 3 rows (all columns)
first_three_orders = blinkit_data[0:3, :]
print("First 3 orders [0:3, :]:")
print(first_three_orders)
print()

First 3 orders [0:3, :]:
[[450.    4.5   8.    3.2   1. ]
 [320.    4.    5.    2.5   2. ]
 [680.    5.   12.    4.1   1. ]]



In [67]:
# Extracting first column (Order Values)
order_values_col = blinkit_data[:, 0]
print("Order values (column 0) [:, 0]:")
print(order_values_col)
print()

Order values (column 0) [:, 0]:
[450. 320. 680. 210. 550. 890. 340. 720.]



In [83]:
# Extracting first 2 columns (Order Value and Rating)
value_rating = blinkit_data[:, 0:2]
print("Order values and ratings [:, 0:2]:")
print(value_rating)
print()

Order values and ratings [:, 0:2]:
[[450.    4.5]
 [320.    4. ]
 [680.    5. ]
 [210.    3.5]
 [550.    4.8]
 [890.    4.2]
 [340.    3.8]
 [720.    4.9]]



In [84]:
# Extracting a subarray: first 4 rows, first 3 columns
subarray = blinkit_data[0:4, 0:3]
print("First 4 orders, first 3 features [0:4, 0:3]:")
print(subarray)
print()

First 4 orders, first 3 features [0:4, 0:3]:
[[450.    4.5   8. ]
 [320.    4.    5. ]
 [680.    5.   12. ]
 [210.    3.5   3. ]]



In [85]:
# Extracting last 2 rows
last_two = blinkit_data[-2:, :]
print("Last 2 orders [-2:, :]:")
print(last_two)
print()

Last 2 orders [-2:, :]:
[[340.    3.8   6.    2.9   3. ]
 [720.    4.9  11.    4.5   2. ]]



In [86]:
# Every alternate row
alternate_rows = blinkit_data[::2, :]
print("Every alternate order [::2, :]:")
print(alternate_rows)
print()

Every alternate order [::2, :]:
[[450.    4.5   8.    3.2   1. ]
 [680.    5.   12.    4.1   1. ]
 [550.    4.8   9.    3.7   2. ]
 [340.    3.8   6.    2.9   3. ]]



### 2.4 Views vs Copies (Important Concept)

- When you slice, NumPy creates a "view", not a copy.
- Changes to the slice affect the original array.

In [87]:
original = np.array([100, 200, 300, 400, 500])
print("Original array:")
print(original)
print()

Original array:
[100 200 300 400 500]



In [88]:
# Creating a slice (this is a view)
slice_view = original[1:4]
print("Slice [1:4]:")
print(slice_view)
print()

Slice [1:4]:
[200 300 400]



In [89]:
# Modifying the slice
slice_view[0] = 999
print("After changing slice[0] to 999:")
print("Slice:", slice_view)
print("Original:", original)
print("Original changed too! (because slice is a view)")
print()

After changing slice[0] to 999:
Slice: [999 300 400]
Original: [100 999 300 400 500]
Original changed too! (because slice is a view)



In [90]:
# To create independent copy, use .copy()
original2 = np.array([100, 200, 300, 400, 500])
slice_copy = original2[1:4].copy()
slice_copy[0] = 888
print("Using .copy():")
print("Slice copy:", slice_copy)
print("Original2:", original2)
print("Original did NOT change! (because we used .copy())")
print()

Using .copy():
Slice copy: [888 300 400]
Original2: [100 200 300 400 500]
Original did NOT change! (because we used .copy())



## SECTION 3: SPEED AND PERFORMANCE (QUICK DEMO)

###  3.1 Speed Comparison: NumPy vs Python Lists

In [106]:
size = 1000000

In [107]:
python_list = list(range(size))
numpy_array = np.arange(size)

In [108]:
# Python list
start = time.time()
python_sum = sum(python_list)
python_time = time.time() - start
print(f"Python list: {python_time:.6f} seconds")

Python list: 0.046374 seconds


In [109]:
# NumPy array
start = time.time()
numpy_sum = np.sum(numpy_array)
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.6f} seconds")

NumPy array: 0.032366 seconds


In [112]:
speedup = python_time / numpy_time
print(f"\nNumpy is {speedup:.3f} X faster")


Numpy is 1.433 X faster


In [113]:
# Why is NumPy faster?
print("Why NumPy is faster:")
print("1. Written in optimized C code")
print("2. Stores data in continuous memory blocks")
print("3. All elements are same type (no type checking needed)")
print("4. Can use multiple CPU cores")
print()

Why NumPy is faster:
1. Written in optimized C code
2. Stores data in continuous memory blocks
3. All elements are same type (no type checking needed)
4. Can use multiple CPU cores



In [119]:
# ============================================================================
# TUTORIAL SUMMARY
# ============================================================================

print("\n" + "=" * 60)
print("TUTORIAL SUMMARY")
print("=" * 60)
print()

print("Today we covered:")
print()
print("1. CREATING ARRAYS:")
print("   - np.array(): Convert lists to arrays")
print("   - np.zeros(), np.ones(): Arrays filled with 0s or 1s")
print("   - np.arange(): Evenly spaced values")
print("   - np.random.randint(): Random integers")
print()
print("2. SLICING:")
print("   - 1D slicing: array[start:stop:step]")
print("   - 2D slicing: array[rows, columns]")
print("   - Negative indexing: Count from end")
print("   - Views vs Copies: Use .copy() for independence")
print()
print("3. PERFORMANCE:")
print("   - NumPy is much faster than Python lists")
print("   - Better for large datasets and calculations")
print()


TUTORIAL SUMMARY

Today we covered:

1. CREATING ARRAYS:
   - np.array(): Convert lists to arrays
   - np.zeros(), np.ones(): Arrays filled with 0s or 1s
   - np.arange(): Evenly spaced values
   - np.random.randint(): Random integers

2. SLICING:
   - 1D slicing: array[start:stop:step]
   - 2D slicing: array[rows, columns]
   - Negative indexing: Count from end
   - Views vs Copies: Use .copy() for independence

3. PERFORMANCE:
   - NumPy is much faster than Python lists
   - Better for large datasets and calculations

